-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR ,MONTH(S.SALES_DATE) AS MONTH, U.GENDER, count(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
WHERE S.SALES_AMOUNT >= 1 AND GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER