WITH tmp AS (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
), tmp2 AS (
    SELECT *
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
)

SELECT t.ANIMAL_ID, t.ANIMAL_TYPE, t.NAME
FROM tmp t JOIN tmp2 t2 on t.ANIMAL_ID = t2.ANIMAL_ID