-- 코드를 작성해주세요
SELECT E.EMP_NO, E.EMP_NAME, 
    
    CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END 'GRADE',
    
    CASE
    WHEN AVG(SCORE) >= 96 THEN (E.SAL * 0.2)
    WHEN AVG(SCORE) >= 90 THEN (E.SAL * 0.15)
    WHEN AVG(SCORE) >= 80 THEN (E.SAL * 0.1)
    ELSE 0
    END 'BONUS'
    
    
FROM HR_EMPLOYEES AS E
JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO
ORDER BY E.EMP_NO ASC